//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_Project.Model
{
    using Library_Management_Project.Helper;
    using System;
    using System.Collections.Generic;

    public partial class CTPhieuMuon : BindableBase
    {
        public CTPhieuMuon()
        {
            BiAn = false;
            BiMat = false;
            TienPhat = 0;
            NgayTra = null;
        }

        private bool? biMat;
        private int? tienPhat;
        private DateTime? ngayTra;

        public int IdPhieuMuon { get; set; }
        public int IdSach { get; set; }
        public Nullable<DateTime> NgayTra
        {
            get { return ngayTra; }
            set { SetBindableProperty(ref ngayTra, value); }
        }
        public Nullable<bool> BiMat
        {
            get { return biMat; }
            set { SetBindableProperty(ref biMat, value); }
        }
        public Nullable<int> TienPhat
        {
            get { return tienPhat; }
            set { SetBindableProperty(ref tienPhat, value); }
        }
        public string GhiChu { get; set; }
        
        public Nullable<bool> BiAn { get; set; }

        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
