//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_Project.Model
{
    using Library_Management_Project.Helper;
    using Library_Management_Project.Helper.Validator;
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia : ValidatableBase<DocGia>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        private string ten;
        private int? idLoai;
        private DateTime? ngaySinh;
        private string diachi;
        private string email;
        private DateTime? ngayLap;

        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
            BiAn = false;

            //List<string> emptyList = new List<string>();
            //emptyList.Add("Thuộc tính này là bắt buộc");
            //errors[nameof(Ten)] = emptyList;
            //errors[nameof(DiaChi)] = emptyList;
            //errors[nameof(Email)] = emptyList;
            //errors[nameof(idLoai)] = emptyList;
            //errors[nameof(NgaySinh)] = emptyList;
            //errors[nameof(NgayLap)] = emptyList;
        }
    
        static DocGia()
        {
            validator = new ReaderValidator();
        }

        public int Id { get; set; }
        public string Ten
        {
            get { return ten; }
            set { SetValidatableProperty(ref ten, value, this); }
        }

        public Nullable<int> IdLoai
        {
            get { return idLoai; }
            set { SetBindableProperty(ref idLoai, value); }
        }

        public Nullable<DateTime> NgaySinh {
            get { return ngaySinh; }
            set
            {
                SetValidatableProperty(ref ngaySinh, value, this);
                RaiseErrorChangedOnProperty("NgayLap", this);
            }
        }

        public string DiaChi
        {
            get { return diachi; }
            set { SetValidatableProperty(ref diachi, value, this); }
        }

        public string Email {
            get { return email; }
            set { SetValidatableProperty(ref email, value, this); }
        }

        public Nullable<DateTime> NgayLap {
            get { return ngayLap; }
            set
            {
                SetValidatableProperty(ref ngayLap, value, this);
                RaiseErrorChangedOnProperty("NgaySinh", this);
            }
        }

        public Nullable<bool> BiAn { get; set; }
    
        public virtual LoaiDocGia LoaiDocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
