//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public int Id { get; set; }
        public Nullable<int> TuoiToiThieuDG { get; set; }
        public Nullable<int> TuoiToiDaDG { get; set; }
        public Nullable<int> KhoangNamXBSach { get; set; }
        public Nullable<int> SLSachMuonToiDa { get; set; }
        public Nullable<int> SoNgayMuonToiDa { get; set; }
        public Nullable<int> TienPhatTreSach_Ngay { get; set; }
        public Nullable<int> PhanTramGiaSach { get; set; }
        public Nullable<int> ChiPhiSachMat { get; set; }
        public Nullable<int> ThoiHanThe { get; set; }
    }
}
